### ISSUE TITLE
aborted core dumped after success printing

### ISSUE THREAD

**Issue by dlwlrma00** [ThinhVu/tsc-printer-js#2]
<img width="728" alt="Screen Shot 2022-01-27 at 1 54 56 AM" src="https://user-images.githubusercontent.com/60172422/151221586-da750656-bc4d-4022-963d-a2d8a6e09343.png">

Any idea regarding this error?

```
npm logs : 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.15
3 info using node@v12.22.9
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ipp-server@0.0.0~prestart: ipp-server@0.0.0
6 info lifecycle ipp-server@0.0.0~start: ipp-server@0.0.0
7 verbose lifecycle ipp-server@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle ipp-server@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dlwlrma/ipp_server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle ipp-server@0.0.0~start: CWD: /home/dlwlrma/ipp_server
10 silly lifecycle ipp-server@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle ipp-server@0.0.0~start: Returned: code: 134  signal: null
12 info lifecycle ipp-server@0.0.0~start: Failed to exec start script
13 verbose stack Error: ipp-server@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid ipp-server@0.0.0
15 verbose cwd /home/dlwlrma/ipp_server
16 verbose Linux 5.4.0-96-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.22.9
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 134
22 error ipp-server@0.0.0 start: `node ./bin/www`
22 error Exit status 134
23 error Failed at the ipp-server@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

**Comment by ThinhVu** [comment]
Dear @dlwlrma00 

The purpose of this library is just provide some helpful functions to generate binary data for TSC Printer.

The implementation in XPrinter.js is just for demo purpose and I'm not ensure that it will work for all variety TSC devices.

Look like you already fix this error in forked branch. Can you make a PR so I can merge it to my repo so a newcomers may get benefit from it.
